services:
  web:
    image: ${ECR_IMAGE}
    ports:
      - "8888:8888"
    env_file:
      - .env

 

  gradio:
    image: ${ECR_IMAGE}
    ports:
      - "7860:7860"
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://web:8888

    depends_on:
      - web
  